## Others

In [1]:
import tensorflow as tf
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.3)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))

### Fig. 3(a). Corr:0.8, BP(25)-CNN-BP(25), baseline, SNR: -3.0~0.0 (Wrong!)

In [41]:
!python main.py -Func GenData -CorrPara 0.8 -EvalSNR "-3 -2.5 -2 -1.5 -1 -0.5 0" -SimuCorrPara 0.8 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest False -NormLambda 0 -SNR_GenData "-3 -2.5 -2 -1.5 -1 -0.5 0"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to GenData
Corr para is set to 0.80
eval_SNRs is set to [-3.  -2.5 -2.  -1.5 -1.  -0.5  0. ]
Corr para for simulation is set to 0.80
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [-3.  -2.5 -2.  -1.5 -1.  -0.5  0. ].
Correlation function of channel noise: 
[0.99999976 0.79999995 0.6399999  0.51199967 0.40959996 0.32768005
 0.26214397 0.20971522 0.16777213 0.13421775]
2018-06-07 10:40:48.848498: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06

In [42]:
!python main.py -Func Train -CorrPara 0.8 -EvalSNR "-3 -2.5 -2 -1.5 -1 -0.5 0" -SimuCorrPara 0.8 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest False -NormLambda 0 -SNR_GenData "-3 -2.5 -2 -1.5 -1 -0.5 0"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Train
Corr para is set to 0.80
eval_SNRs is set to [-3.  -2.5 -2.  -1.5 -1.  -0.5  0. ]
Corr para for simulation is set to 0.80
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [-3.  -2.5 -2.  -1.5 -1.  -0.5  0. ].
Construct the data IO class for training!

2018-06-07 10:58:28.676222: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 10:58:29.317703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
n

In [43]:
!python main.py -Func Simulation -CorrPara 0.8 -EvalSNR "-3 -2.5 -2 -1.5 -1 -0.5 0" -SimuCorrPara 0.8 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest False -NormLambda 0 -SNR_GenData "-3 -2.5 -2 -1.5 -1 -0.5 0"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Simulation
Corr para is set to 0.80
eval_SNRs is set to [-3.  -2.5 -2.  -1.5 -1.  -0.5  0. ]
Corr para for simulation is set to 0.80
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [-3.  -2.5 -2.  -1.5 -1.  -0.5  0. ].
Correlation function of channel noise: 
[0.99999976 0.79999995 0.6399999  0.51199967 0.40959996 0.32768005
 0.26214397 0.20971522 0.16777213 0.13421775]
2018-06-07 11:32:07.829841: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018

Batch 2 in total 47 batches. Practical EbN0: 0.00
Batch 3 in total 47 batches. Practical EbN0: -0.01
Batch 4 in total 47 batches. Practical EbN0: -0.00
10800000 bits are simulated!
Time: 79s
end

Close the tf session!
Close a tf session!
Finished Simulation!


### Fig. 3(a). Corr:0.8, BP(25)-CNN-BP(25), enhanced, SNR: -3.0~0.0 (Correct!)


In [4]:
!python main.py -Func GenData -CorrPara 0.8 -EvalSNR "-3 -2.5 -2 -1.5 -1 -0.5 0" -SimuCorrPara 0.8 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest True -NormLambda 0.1 -SNR_GenData "-3 -2.5 -2 -1.5 -1 -0.5 0"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to GenData
Corr para is set to 0.80
eval_SNRs is set to [-3.  -2.5 -2.  -1.5 -1.  -0.5  0. ]
Corr para for simulation is set to 0.80
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: True
Normality lambda is set to 0.100000
SNR set for generating data is set to [-3.  -2.5 -2.  -1.5 -1.  -0.5  0. ].
Correlation function of channel noise: 
[0.99999976 0.79999995 0.6399999  0.51199967 0.40959996 0.32768005
 0.26214397 0.20971522 0.16777213 0.13421775]
2018-06-06 10:58:23.123755: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-

In [5]:
!python main.py -Func Train -CorrPara 0.8 -EvalSNR "-3 -2.5 -2 -1.5 -1 -0.5 0" -SimuCorrPara 0.8 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest True -NormLambda 0.1 -SNR_GenData "-3 -2.5 -2 -1.5 -1 -0.5 0"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Train
Corr para is set to 0.80
eval_SNRs is set to [-3.  -2.5 -2.  -1.5 -1.  -0.5  0. ]
Corr para for simulation is set to 0.80
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: True
Normality lambda is set to 0.100000
SNR set for generating data is set to [-3.  -2.5 -2.  -1.5 -1.  -0.5  0. ].
Construct the data IO class for training!

2018-06-06 11:16:08.019407: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-06 11:16:08.678318: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
na

In [6]:
!python main.py -Func Simulation -CorrPara 0.8 -EvalSNR "-3 -2.5 -2 -1.5 -1 -0.5 0" -SimuCorrPara 0.8 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest True -NormLambda 0.1 -SNR_GenData "-3 -2.5 -2 -1.5 -1 -0.5 0"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Simulation
Corr para is set to 0.80
eval_SNRs is set to [-3.  -2.5 -2.  -1.5 -1.  -0.5  0. ]
Corr para for simulation is set to 0.80
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: True
Normality lambda is set to 0.100000
SNR set for generating data is set to [-3.  -2.5 -2.  -1.5 -1.  -0.5  0. ].
Correlation function of channel noise: 
[0.99999976 0.79999995 0.6399999  0.51199967 0.40959996 0.32768005
 0.26214397 0.20971522 0.16777213 0.13421775]
2018-06-06 11:56:03.842077: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-

Batch 7 in total 47 batches. Practical EbN0: -0.48
Batch 8 in total 47 batches. Practical EbN0: -0.50
Batch 9 in total 47 batches. Practical EbN0: -0.49
Batch 10 in total 47 batches. Practical EbN0: -0.51
Batch 11 in total 47 batches. Practical EbN0: -0.49
Batch 12 in total 47 batches. Practical EbN0: -0.51
Batch 13 in total 47 batches. Practical EbN0: -0.50
Batch 14 in total 47 batches. Practical EbN0: -0.51
Batch 15 in total 47 batches. Practical EbN0: -0.50
34560000 bits are simulated!
Batch 0 in total 47 batches. Practical EbN0: 0.01
Batch 1 in total 47 batches. Practical EbN0: -0.01
Batch 2 in total 47 batches. Practical EbN0: 0.00
Batch 3 in total 47 batches. Practical EbN0: -0.01
Batch 4 in total 47 batches. Practical EbN0: -0.00
Batch 5 in total 47 batches. Practical EbN0: 0.00
Batch 6 in total 47 batches. Practical EbN0: 0.00
Batch 7 in total 47 batches. Practical EbN0: 0.02
Batch 8 in total 47 batches. Practical EbN0: -0.00
Batch 9 in total 47 batches. Practical EbN0: 0.01
Ba

### Fig. 3(a). Corr:0.8, BP(50), SNR: 0.0~3.0 (Different.)

In [29]:
!python main.py -Func GenData -CorrPara 0.8 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.8 -BP_IterForGenData 50 -BP_IterForSimu "50" -NetNumber 0 -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to GenData
Corr para is set to 0.80
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.80
BP iter for gen data is set to: [50]
BP iter for simulation is set to: [50]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Correlation function of channel noise: 
[0.99999976 0.79999995 0.6399999  0.51199967 0.40959996 0.32768005
 0.26214397 0.20971522 0.16777213 0.13421775]
2018-06-07 06:56:59.200229: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 06:56:59.9305

In [30]:
!python main.py -Func Train -CorrPara 0.8 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.8 -BP_IterForGenData 50 -BP_IterForSimu "50" -NetNumber 0 -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Train
Corr para is set to 0.80
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.80
BP iter for gen data is set to: [50]
BP iter for simulation is set to: [50]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Construct the data IO class for training!

2018-06-07 07:20:17.308775: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 07:20:17.931990: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Tesla V100-S

In [31]:
!python main.py -Func Simulation -CorrPara 0.8 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.8 -BP_IterForGenData 50 -BP_IterForSimu "50" -NetNumber 0 -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Simulation
Corr para is set to 0.80
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.80
BP iter for gen data is set to: [50]
BP iter for simulation is set to: [50]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Correlation function of channel noise: 
[0.99999976 0.79999995 0.6399999  0.51199967 0.40959996 0.32768005
 0.26214397 0.20971522 0.16777213 0.13421775]
2018-06-07 07:40:39.471061: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 07:40:40.2

Batch 3 in total 47 batches. Practical EbN0: 2.99
Batch 4 in total 47 batches. Practical EbN0: 3.00
Batch 5 in total 47 batches. Practical EbN0: 3.00
Batch 6 in total 47 batches. Practical EbN0: 3.00
Batch 7 in total 47 batches. Practical EbN0: 3.02
Batch 8 in total 47 batches. Practical EbN0: 3.00
Batch 9 in total 47 batches. Practical EbN0: 3.01
Batch 10 in total 47 batches. Practical EbN0: 2.99
Batch 11 in total 47 batches. Practical EbN0: 3.01
25920000 bits are simulated!
Time: 84s
end

Close the tf session!
Close a tf session!
Finished Simulation!


### Fig. 3(b). Corr:0.5, BP(25)-CNN-BP(25), baseline, SNR: 0.0~3.0 (Different.)

In [26]:
!python main.py -Func GenData -CorrPara 0.5 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.5 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to GenData
Corr para is set to 0.50
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.50
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Correlation function of channel noise: 
[1.         0.5        0.25000003 0.125      0.0625     0.03125
 0.015625   0.0078125  0.00390625 0.00195313]
2018-06-07 03:07:42.489868: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 03:07:43.2253

In [27]:
!python main.py -Func Train -CorrPara 0.5 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.5 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Train
Corr para is set to 0.50
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.50
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Construct the data IO class for training!

2018-06-07 03:25:20.522799: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 03:25:21.145354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Tesla V10

In [28]:
!python main.py -Func Simulation -CorrPara 0.5 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.5 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Simulation
Corr para is set to 0.50
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.50
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Correlation function of channel noise: 
[1.         0.5        0.25000003 0.125      0.0625     0.03125
 0.015625   0.0078125  0.00390625 0.00195313]
2018-06-07 03:40:48.405777: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 03:40:49.0

Batch 3 in total 47 batches. Practical EbN0: 3.00
Batch 4 in total 47 batches. Practical EbN0: 3.00
Batch 5 in total 47 batches. Practical EbN0: 3.00
Batch 6 in total 47 batches. Practical EbN0: 3.00
Batch 7 in total 47 batches. Practical EbN0: 3.01
Batch 8 in total 47 batches. Practical EbN0: 3.00
Batch 9 in total 47 batches. Practical EbN0: 3.00
21600000 bits are simulated!
Time: 85s
end

Close the tf session!
Close a tf session!
Finished Simulation!


### Fig. 3(b). Corr:0.5, BP(25)-CNN-BP(25), enhanced, SNR: 0.0~3.0 (Correct!)


In [20]:
!python main.py -Func GenData -CorrPara 0.5 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.5 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest True -NormLambda 10 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to GenData
Corr para is set to 0.50
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.50
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: True
Normality lambda is set to 10.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Correlation function of channel noise: 
[1.         0.5        0.25000003 0.125      0.0625     0.03125
 0.015625   0.0078125  0.00390625 0.00195313]
2018-06-06 14:51:39.111237: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-06 14:51:39.8446

In [21]:
!python main.py -Func Train -CorrPara 0.5 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.5 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest True -NormLambda 10 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Train
Corr para is set to 0.50
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.50
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: True
Normality lambda is set to 10.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Construct the data IO class for training!

2018-06-06 15:10:02.713776: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-06 15:10:03.376130: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Tesla V10

In [22]:
!python main.py -Func Simulation -CorrPara 0.5 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.5 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest True -NormLambda 10 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Simulation
Corr para is set to 0.50
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.50
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: True
Normality lambda is set to 10.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Correlation function of channel noise: 
[1.         0.5        0.25000003 0.125      0.0625     0.03125
 0.015625   0.0078125  0.00390625 0.00195313]
2018-06-06 15:25:32.215725: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-06 15:25:32.9

Batch 7 in total 47 batches. Practical EbN0: 2.51
Batch 8 in total 47 batches. Practical EbN0: 2.50
Batch 9 in total 47 batches. Practical EbN0: 2.50
Batch 10 in total 47 batches. Practical EbN0: 2.50
Batch 11 in total 47 batches. Practical EbN0: 2.50
Batch 12 in total 47 batches. Practical EbN0: 2.49
Batch 13 in total 47 batches. Practical EbN0: 2.50
Batch 14 in total 47 batches. Practical EbN0: 2.50
Batch 15 in total 47 batches. Practical EbN0: 2.50
Batch 16 in total 47 batches. Practical EbN0: 2.51
Batch 17 in total 47 batches. Practical EbN0: 2.50
Batch 18 in total 47 batches. Practical EbN0: 2.50
Batch 19 in total 47 batches. Practical EbN0: 2.51
Batch 20 in total 47 batches. Practical EbN0: 2.50
Batch 21 in total 47 batches. Practical EbN0: 2.50
Batch 22 in total 47 batches. Practical EbN0: 2.50
Batch 23 in total 47 batches. Practical EbN0: 2.51
Batch 24 in total 47 batches. Practical EbN0: 2.50
Batch 25 in total 47 batches. Practical EbN0: 2.50
Batch 26 in total 47 batches. Prac

### Fig. 3(b). Corr:0.5, BP(50), SNR: 0.0~3.0 (Different.)

In [23]:
!python main.py -Func GenData -CorrPara 0.5 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.5 -BP_IterForGenData 50 -BP_IterForSimu "50" -NetNumber 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to GenData
Corr para is set to 0.50
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.50
BP iter for gen data is set to: [50]
BP iter for simulation is set to: [50]
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Correlation function of channel noise: 
[1.         0.5        0.25000003 0.125      0.0625     0.03125
 0.015625   0.0078125  0.00390625 0.00195313]
2018-06-06 15:30:35.813277: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-06 15:30:36.516992: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] 

In [24]:
!python main.py -Func Train -CorrPara 0.5 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.5 -BP_IterForGenData 50 -BP_IterForSimu "50" -NetNumber 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Train
Corr para is set to 0.50
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.50
BP iter for gen data is set to: [50]
BP iter for simulation is set to: [50]
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Construct the data IO class for training!

2018-06-06 15:54:01.292731: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-06 15:54:01.918191: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciB

In [25]:
!python main.py -Func Simulation -CorrPara 0.5 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.5 -BP_IterForGenData 50 -BP_IterForSimu "50" -NetNumber 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Simulation
Corr para is set to 0.50
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.50
BP iter for gen data is set to: [50]
BP iter for simulation is set to: [50]
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Correlation function of channel noise: 
[1.         0.5        0.25000003 0.125      0.0625     0.03125
 0.015625   0.0078125  0.00390625 0.00195313]
2018-06-06 15:57:02.911406: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-06 15:57:03.667906: I tensorflow/core/common_runtime/gpu/gpu_device.cc:135

21600000 bits are simulated!
Batch 0 in total 47 batches. Practical EbN0: 3.00
Batch 1 in total 47 batches. Practical EbN0: 3.00
Batch 2 in total 47 batches. Practical EbN0: 3.00
Batch 3 in total 47 batches. Practical EbN0: 3.00
Batch 4 in total 47 batches. Practical EbN0: 3.00
Batch 5 in total 47 batches. Practical EbN0: 3.00
Batch 6 in total 47 batches. Practical EbN0: 3.00
Batch 7 in total 47 batches. Practical EbN0: 3.01
Batch 8 in total 47 batches. Practical EbN0: 3.00
Batch 9 in total 47 batches. Practical EbN0: 3.00
Batch 10 in total 47 batches. Practical EbN0: 3.00
Batch 11 in total 47 batches. Practical EbN0: 3.00
Batch 12 in total 47 batches. Practical EbN0: 2.99
Batch 13 in total 47 batches. Practical EbN0: 3.00
Batch 14 in total 47 batches. Practical EbN0: 3.00
Batch 15 in total 47 batches. Practical EbN0: 3.00
Batch 16 in total 47 batches. Practical EbN0: 3.01
Batch 17 in total 47 batches. Practical EbN0: 3.00
Batch 18 in total 47 batches. Practical EbN0: 3.00
Batch 19 in 

### Fig. 3(c). Corr:0.0, BP(25)-CNN-BP(25), baseline, SNR: 0.0~3.0 (Correct!)

In [ ]:
!python main.py -Func GenData -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

Function is set to GenData
Corr para is set to 0.00
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.00
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Correlation function of channel noise: 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2018-06-21 05:13:30.506281: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-21 05:13:35.548312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:0a:00.0
totalMemory: 15.77GiB freeMemory: 4.45GiB
2018-06-21 05:13:35.548383: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-21 05:13:36.974618: I tensor

In [ ]:
!python main.py -Func Train -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

In [ ]:
!python main.py -Func Simulation -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

### Fig. 3(c). Corr:0.0, BP(25)-CNN-BP(25), enhanced, SNR: 0.0~3.0 (Correct!)


In [35]:
!python main.py -Func GenData -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest True -NormLambda 10 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to GenData
Corr para is set to 0.00
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.00
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: True
Normality lambda is set to 10.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Correlation function of channel noise: 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2018-06-07 08:28:13.205713: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 08:28:13.904735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 wi

In [36]:
!python main.py -Func Train -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest True -NormLambda 10 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Train
Corr para is set to 0.00
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.00
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: True
Normality lambda is set to 10.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Construct the data IO class for training!

2018-06-07 08:45:48.555333: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 08:45:49.176914: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Tesla V10

In [37]:
!python main.py -Func Simulation -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest True -NormLambda 10 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Simulation
Corr para is set to 0.00
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.00
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: True
Normality lambda is set to 10.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Correlation function of channel noise: 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2018-06-07 09:03:00.329462: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 09:03:01.102359: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0

Batch 11 in total 47 batches. Practical EbN0: 2.50
Batch 12 in total 47 batches. Practical EbN0: 2.50
Batch 13 in total 47 batches. Practical EbN0: 2.50
Batch 14 in total 47 batches. Practical EbN0: 2.50
32400000 bits are simulated!
Batch 0 in total 47 batches. Practical EbN0: 3.00
Batch 1 in total 47 batches. Practical EbN0: 3.00
Batch 2 in total 47 batches. Practical EbN0: 3.00
Batch 3 in total 47 batches. Practical EbN0: 3.00
Batch 4 in total 47 batches. Practical EbN0: 3.00
Batch 5 in total 47 batches. Practical EbN0: 3.00
Batch 6 in total 47 batches. Practical EbN0: 3.00
Batch 7 in total 47 batches. Practical EbN0: 3.01
Batch 8 in total 47 batches. Practical EbN0: 3.00
Batch 9 in total 47 batches. Practical EbN0: 3.00
Batch 10 in total 47 batches. Practical EbN0: 3.00
Batch 11 in total 47 batches. Practical EbN0: 3.00
Batch 12 in total 47 batches. Practical EbN0: 3.00
Batch 13 in total 47 batches. Practical EbN0: 3.00
Batch 14 in total 47 batches. Practical EbN0: 3.00
Batch 15 in 

### Fig. 3(c). Corr:0.0, BP(50), SNR: 0.0~3.0 (Correct!)

In [38]:
!python main.py -Func GenData -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 50 -BP_IterForSimu "50" -NetNumber 0 -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to GenData
Corr para is set to 0.00
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.00
BP iter for gen data is set to: [50]
BP iter for simulation is set to: [50]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Correlation function of channel noise: 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2018-06-07 09:06:49.310362: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 09:06:49.996750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with 

In [39]:
!python main.py -Func Train -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 50 -BP_IterForSimu "50" -NetNumber 0 -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Train
Corr para is set to 0.00
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.00
BP iter for gen data is set to: [50]
BP iter for simulation is set to: [50]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Construct the data IO class for training!

2018-06-07 09:30:43.046322: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 09:30:43.677004: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Tesla V100-S

In [40]:
!python main.py -Func Simulation -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 50 -BP_IterForSimu "50" -NetNumber 0 -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3"

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Simulation
Corr para is set to 0.00
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.00
BP iter for gen data is set to: [50]
BP iter for simulation is set to: [50]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
Correlation function of channel noise: 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2018-06-07 09:49:01.315046: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 09:49:01.999912: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 wi

Batch 12 in total 47 batches. Practical EbN0: 2.50
Batch 13 in total 47 batches. Practical EbN0: 2.50
Batch 14 in total 47 batches. Practical EbN0: 2.50
Batch 15 in total 47 batches. Practical EbN0: 2.50
Batch 16 in total 47 batches. Practical EbN0: 2.50
36720000 bits are simulated!
Batch 0 in total 47 batches. Practical EbN0: 3.00
Batch 1 in total 47 batches. Practical EbN0: 3.00
Batch 2 in total 47 batches. Practical EbN0: 3.00
Batch 3 in total 47 batches. Practical EbN0: 3.00
Batch 4 in total 47 batches. Practical EbN0: 3.00
Batch 5 in total 47 batches. Practical EbN0: 3.00
Batch 6 in total 47 batches. Practical EbN0: 3.00
Batch 7 in total 47 batches. Practical EbN0: 3.01
Batch 8 in total 47 batches. Practical EbN0: 3.00
Batch 9 in total 47 batches. Practical EbN0: 3.00
Batch 10 in total 47 batches. Practical EbN0: 3.00
Batch 11 in total 47 batches. Practical EbN0: 3.00
Batch 12 in total 47 batches. Practical EbN0: 3.00
Batch 13 in total 47 batches. Practical EbN0: 3.00
Batch 14 in 

### URLLC. Corr:0.0, BP(25)-CNN-BP(25), baseline, SNR: 0.0~3.0

In [61]:
!python main.py -Func GenData -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3" -URLLC_Intf True

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to GenData
Corr para is set to 0.00
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.00
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
URLLC Interference: True
Correlation function of channel noise: 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2018-06-07 15:45:14.007301: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 15:45:14.714257: I tensorflow/core/common_runtime/gpu/gpu_device.c

In [62]:
!python main.py -Func Train -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3" -URLLC_Intf True

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Train
Corr para is set to 0.00
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.00
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
URLLC Interference: True
Construct the data IO class for training!

2018-06-07 16:03:51.345845: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 16:03:51.991247: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with pro

In [63]:
!python main.py -Func Simulation -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3" -URLLC_Intf True

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Simulation
Corr para is set to 0.00
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.00
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
URLLC Interference: True
Correlation function of channel noise: 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2018-06-07 16:23:21.145710: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 16:23:21.901184: I tensorflow/core/common_runtime/gpu/gpu_devic

10800000 bits are simulated!
Time: 84s
end

Close the tf session!
Close a tf session!
Finished Simulation!


### URLLC. Corr:0.0, BP(25), SNR: 0.0~3.0

In [64]:
!python main.py -Func GenData -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 25 -BP_IterForSimu "25" -NetNumber 0 -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3" -URLLC_Intf True

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to GenData
Corr para is set to 0.00
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.00
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
URLLC Interference: True
Correlation function of channel noise: 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2018-06-07 16:25:37.075868: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 16:25:37.799703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1

In [65]:
!python main.py -Func Train -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 25 -BP_IterForSimu "25" -NetNumber 0 -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3" -URLLC_Intf True

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Train
Corr para is set to 0.00
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.00
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
URLLC Interference: True
Construct the data IO class for training!

2018-06-07 16:44:19.460262: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 16:44:20.104662: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with proper

In [66]:
!python main.py -Func Simulation -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 25 -BP_IterForSimu "25" -NetNumber 0 -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3" -URLLC_Intf True

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Function is set to Simulation
Corr para is set to 0.00
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.00
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
URLLC Interference: True
Correlation function of channel noise: 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2018-06-07 16:59:13.308144: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-07 16:59:14.029830: I tensorflow/core/common_runtime/gpu/gpu_device.c

### URLLC. Corr:0.0, BP(25)-CNN-BP(25), baseline, SNR: 0.0~3.0 (!)

In [1]:
!python main.py -Func GenData -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3" -URLLC_Intf True

Function is set to GenData
Corr para is set to 0.00
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.00
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
URLLC Interference: True
Correlation function of channel noise: 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2018-06-26 06:56:41.122614: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-26 06:56:41.811011: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:0a:00.0
totalMemory: 15.77GiB freeMemory: 314.31MiB
2018-06-26 06:56:41.811052: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-2

    self.sess.run(self.xe_v2c_pre_iter_assign)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[2040,200] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: MatMul_1 = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](MatMul_1/a, Variable/read)]]
Hint: If you want to see a list of allocated 

In [2]:
!python main.py -Func Train -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3" -URLLC_Intf True

Function is set to Train
Corr para is set to 0.00
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.00
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
URLLC Interference: True
Construct the data IO class for training!

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 577 and 576 for 'sub_1' (op: 'Sub') with input shapes: [?,577], [?,576].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 42, in <module>
    conv_net.train_network(top_config.model_id)
  File "/workspace/BPCNN/ConvNet.p

In [3]:
!python main.py -Func Simulation -CorrPara 0.0 -EvalSNR "0 0.5 1 1.5 2 2.5 3" -SimuCorrPara 0.0 -BP_IterForGenData 25 -BP_IterForSimu "25 25" -NormTest False -NormLambda 0 -SNR_GenData "0 0.5 1 1.5 2 2.5 3" -URLLC_Intf True

Function is set to Simulation
Corr para is set to 0.00
eval_SNRs is set to [0.  0.5 1.  1.5 2.  2.5 3. ]
Corr para for simulation is set to 0.00
BP iter for gen data is set to: [25]
BP iter for simulation is set to: [25 25]
Normality test: False
Normality lambda is set to 0.000000
SNR set for generating data is set to [0.  0.5 1.  1.5 2.  2.5 3. ].
URLLC Interference: True
Correlation function of channel noise: 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2018-06-26 06:57:00.304346: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-26 06:57:01.003325: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:0a:00.0
totalMemory: 15.77GiB freeMemory: 314.31MiB
2018-06-26 06:57:01.003378: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-0

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor of shape [2040,5000] and type float
	 [[Node: Variable_1/initial_value = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [2040,5000] values: [1 1 1]...>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 48, in <module>
    ibd.analyze_residual_noise(code, top_config, net_config, simutimes_for